#  PyTorch Basic 01. Generate Tensor
---
- torch.empty()
- torch.rand()
- torch.zeros()
- torch.ones()
- torch.tensor()
- torch.Tensor()
<br>

In [1]:
import torch

In [12]:
x = torch.empty(3)
y = torch.empty(3,2)
print(x)
print(y)

tensor([0.0000e+00, 0.0000e+00, 5.6052e-45])
tensor([[0.0000e+00, 2.3694e-38],
        [1.8754e+28, 2.0110e+20],
        [1.7061e-07, 1.3040e-11]])


In [13]:
x = torch.rand(2)
y = torch.rand(3,2)

print(x)
print(y)

tensor([0.5777, 0.1370])
tensor([[0.9998, 0.0793],
        [0.8528, 0.5195],
        [0.2840, 0.3653]])


In [14]:
x = torch.zeros(2)
y = torch.zeros(3,2)

print(x)
print(y)

tensor([0., 0.])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [15]:
x = torch.ones(2)
y = torch.ones(3,2)

print(x)
print(y)

tensor([1., 1.])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [18]:
print(torch.empty(3,2).dtype)
print(torch.rand(3,2).dtype)
print(torch.zeros(3,2).dtype)
print(torch.ones(3,2).dtype)

torch.float32
torch.float32
torch.float32
torch.float32


In [20]:
print(torch.empty(3,2, dtype=torch.int).dtype)
print(torch.rand(3,2, dtype=torch.double).dtype)
print(torch.zeros(3,2, dtype=torch.float16).dtype)
print(torch.ones(3,2, dtype=torch.float64).dtype)

torch.int32
torch.float64
torch.float16
torch.float64


In [25]:
print(torch.empty(3,2).size())
print(torch.rand(3,2).size())
print(torch.zeros(3,2).shape)
print(torch.ones(3,2).shape)

torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([3, 2])
torch.Size([3, 2])


In [28]:
x = torch.Tensor([0,1,2])
y = torch.Tensor([0., 1., 2.])
print(x, x.dtype)
print(y, y.dtype)

tensor([0., 1., 2.]) torch.float32
tensor([0., 1., 2.]) torch.float32


In [29]:
x = torch.tensor([0,1,2])
y = torch.tensor([0., 1., 2.])
print(x, x.dtype)
print(y, y.dtype)

tensor([0, 1, 2]) torch.int64
tensor([0., 1., 2.]) torch.float32
