# Basic Operation
---


In [2]:

import torch

In [13]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print(x)
print(y)

tensor([[0.8089, 0.4800],
        [0.4084, 0.6234]])
tensor([[0.2326, 0.9515],
        [0.6435, 0.2718]])


In [16]:
add_1 = x+y
add_2 = torch.add(x,y)

print(add_1, add_2, sep='\n')


tensor([[1.8504, 1.9116],
        [1.4602, 1.5185]])
tensor([[1.8504, 1.9116],
        [1.4602, 1.5185]])


In [17]:
sub_1 = x-y
sub_2 = torch.sub(x,y)

print(sub_1, sub_1, sep='\n')


tensor([[-0.2326, -0.9515],
        [-0.6435, -0.2718]])
tensor([[-0.2326, -0.9515],
        [-0.6435, -0.2718]])


In [18]:
mul_1 = x*y
mul_2 = torch.mul(x,y)

print(mul_1, mul_2, sep='\n')


tensor([[0.8425, 0.6872],
        [0.4296, 0.5580]])
tensor([[0.8425, 0.6872],
        [0.4296, 0.5580]])


In [19]:
div_1 = x/y
div_2 = torch.div(x,y)

print(div_1, div_2, sep='\n')


tensor([[0.7767, 0.3353],
        [0.3882, 0.6964]])
tensor([[0.7767, 0.3353],
        [0.3882, 0.6964]])


## Inplace version of operators
---

In [24]:
x = torch.Tensor([[1,1],
                  [1,1]])
y = torch.Tensor([[1,0],
                  [0,1]])


x.add_(y)
print(x)
x.add_(y)
print(x)

tensor([[2., 1.],
        [1., 2.]])
tensor([[3., 1.],
        [1., 3.]])


In [25]:
x = torch.Tensor([[1,1],
                  [1,1]])
y = torch.Tensor([[1,0],
                  [0,1]])


x.sub_(y)
print(x)
x.sub_(y)
print(x)

tensor([[0., 1.],
        [1., 0.]])
tensor([[-1.,  1.],
        [ 1., -1.]])


In [27]:
x = torch.Tensor([[1,1],
                  [1,1]])
y = torch.Tensor([[1,0],
                  [0,1]])


x.mul_(y)
print(x)
x.mul_(y)
print(x)

tensor([[1., 0.],
        [0., 1.]])
tensor([[1., 0.],
        [0., 1.]])


In [29]:
x = torch.Tensor([[1,1],
                  [1,1]])
y = torch.Tensor([[1,0],
                  [0,1]])


x.div_(y)
print(x)
x.div_(y)
print(x)

tensor([[1., inf],
        [inf, 1.]])
tensor([[1., inf],
        [inf, 1.]])
