# Tensor Indexing
---

In [1]:
import torch

In [4]:
x = torch.rand(5,3)
print(x)
print(x[:, 0])
print(x[1,:])

tensor([[0.3583, 0.7136, 0.2398],
        [0.8045, 0.1365, 0.1021],
        [0.0922, 0.4952, 0.2953],
        [0.5177, 0.6493, 0.0620],
        [0.8767, 0.3268, 0.4896]])
tensor([0.3583, 0.8045, 0.0922, 0.5177, 0.8767])
tensor([0.8045, 0.1365, 0.1021])


In [11]:
print(x[1,1])
print(x[1,1].dtype)

print(x[1,1].item())
print(type(x[1,1].item()))

tensor(0.1365)
torch.float32
0.1364954113960266
<class 'float'>
