# Reshaping
---

In [2]:
import torch

In [3]:
x = torch.rand(4,4)
print(x)

tensor([[0.8233, 0.5192, 0.1143, 0.4652],
        [0.7187, 0.7110, 0.7971, 0.1785],
        [0.8174, 0.4686, 0.4957, 0.5915],
        [0.6774, 0.4720, 0.9571, 0.3854]])


In [15]:
print(x.squeeze())
print(x.unsqueeze(0))
print(x.unsqueeze(1))
print(x.unsqueeze(2))

tensor([[0.8233, 0.5192, 0.1143, 0.4652],
        [0.7187, 0.7110, 0.7971, 0.1785],
        [0.8174, 0.4686, 0.4957, 0.5915],
        [0.6774, 0.4720, 0.9571, 0.3854]])
tensor([[[0.8233, 0.5192, 0.1143, 0.4652],
         [0.7187, 0.7110, 0.7971, 0.1785],
         [0.8174, 0.4686, 0.4957, 0.5915],
         [0.6774, 0.4720, 0.9571, 0.3854]]])
tensor([[[0.8233, 0.5192, 0.1143, 0.4652]],

        [[0.7187, 0.7110, 0.7971, 0.1785]],

        [[0.8174, 0.4686, 0.4957, 0.5915]],

        [[0.6774, 0.4720, 0.9571, 0.3854]]])
tensor([[[0.8233],
         [0.5192],
         [0.1143],
         [0.4652]],

        [[0.7187],
         [0.7110],
         [0.7971],
         [0.1785]],

        [[0.8174],
         [0.4686],
         [0.4957],
         [0.5915]],

        [[0.6774],
         [0.4720],
         [0.9571],
         [0.3854]]])


In [16]:
x.view(16)

tensor([0.8233, 0.5192, 0.1143, 0.4652, 0.7187, 0.7110, 0.7971, 0.1785, 0.8174,
        0.4686, 0.4957, 0.5915, 0.6774, 0.4720, 0.9571, 0.3854])